name: SlimeTinker
author: Sefiraat
description: An addon that is trying to recreate Tinker's Construct within Slimefun. Adds new customisable tools with leveling and modifiers.
main: io.github.sefiraat.slimetinker.SlimeTinker
website: https://github.com/Sefiraat/SlimeTinker
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - SlimefunWarfare
  - DynaTech
  - LiteXpansion
commands:
  slimetinker:
    description: /slimetinker
    usage: /slimetinker <sub>
    aliases: [ st, tinker ]