name: Java CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set up JDK 16
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 16
          distribution: adopt
      - name: Build with Maven
        run: mvn package --file pom.xml
